In [215]:
import numpy as np
import pandas as pd

In [216]:
df = pd.read_csv('covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [217]:
df[df['fever'].isnull()]

age  gender  fever   cough       city has_covid
5    84  Female    NaN    Mild  Bangalore       Yes
7    20  Female    NaN  Strong     Mumbai       Yes
10   75  Female    NaN    Mild      Delhi        No
19   42  Female    NaN  Strong  Bangalore       Yes
25   23    Male    NaN    Mild     Mumbai        No
29   34  Female    NaN  Strong     Mumbai       Yes
41   82    Male    NaN    Mild    Kolkata       Yes
56   71    Male    NaN  Strong    Kolkata        No
91   38    Male    NaN    Mild      Delhi       Yes
94   79    Male    NaN  Strong    Kolkata       Yes

In [218]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [219]:
si.fit(df)

SimpleImputer(strategy='most_frequent')

In [220]:
df = pd.DataFrame(si.transform(df),columns=df.columns)

In [221]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [222]:
cough = pd.DataFrame(df['cough'])
cough.sample(5)

cough
67    Mild
24  Strong
26    Mild
64    Mild
17  Strong

In [223]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild','Strong']])

In [224]:
oe.fit(cough)

OrdinalEncoder(categories=[['Mild', 'Strong']])

In [225]:
cough = oe.transform(cough)

# Encoded array of the column cough

In [226]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False,dtype=int,drop='first')

In [227]:
ohe.fit(df[['gender']])

OneHotEncoder(drop='first', dtype=<class 'int'>, sparse_output=False)

In [228]:
gender = ohe.transform(df[['gender']])

# encoded array of column gender
gender

array([[1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
    

In [229]:
ohe.fit(df[['city']])

OneHotEncoder(drop='first', dtype=<class 'int'>, sparse_output=False)

In [230]:
city = ohe.transform(df[['city']])

# encoded array of column city

In [231]:
df

age  gender  fever   cough       city has_covid
0   60    Male  103.0    Mild    Kolkata        No
1   27    Male  100.0    Mild      Delhi       Yes
2   42    Male  101.0    Mild      Delhi        No
3   31  Female   98.0    Mild    Kolkata        No
4   65  Female  101.0    Mild     Mumbai        No
..  ..     ...    ...     ...        ...       ...
95  12  Female  104.0    Mild  Bangalore        No
96  51  Female  101.0  Strong    Kolkata       Yes
97  20  Female  101.0    Mild  Bangalore        No
98   5  Female   98.0  Strong     Mumbai        No
99  10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [232]:
age = np.array(df[['age']])
fever = np.array(df[['fever']])
has_covid = np.array(df[['has_covid']])

In [233]:
new_array = np.hstack([age, gender, fever, cough, city, has_covid])

In [234]:
new_array

array([[60, 1, 103.0, 0.0, 0, 1, 0, 'No'],
       [27, 1, 100.0, 0.0, 1, 0, 0, 'Yes'],
       [42, 1, 101.0, 0.0, 1, 0, 0, 'No'],
       [31, 0, 98.0, 0.0, 0, 1, 0, 'No'],
       [65, 0, 101.0, 0.0, 0, 0, 1, 'No'],
       [84, 0, 98.0, 0.0, 0, 0, 0, 'Yes'],
       [14, 1, 101.0, 1.0, 0, 0, 0, 'No'],
       [20, 0, 98.0, 1.0, 0, 0, 1, 'Yes'],
       [19, 0, 100.0, 1.0, 0, 0, 0, 'No'],
       [64, 0, 101.0, 0.0, 1, 0, 0, 'No'],
       [75, 0, 98.0, 0.0, 1, 0, 0, 'No'],
       [65, 0, 98.0, 0.0, 0, 0, 1, 'Yes'],
       [25, 0, 99.0, 1.0, 0, 1, 0, 'No'],
       [64, 1, 102.0, 0.0, 0, 0, 0, 'Yes'],
       [51, 1, 104.0, 0.0, 0, 0, 0, 'No'],
       [70, 1, 103.0, 1.0, 0, 1, 0, 'Yes'],
       [69, 0, 103.0, 0.0, 0, 1, 0, 'Yes'],
       [40, 0, 98.0, 1.0, 1, 0, 0, 'No'],
       [64, 0, 98.0, 0.0, 0, 0, 0, 'Yes'],
       [42, 0, 98.0, 1.0, 0, 0, 0, 'Yes'],
       [12, 1, 98.0, 1.0, 0, 0, 0, 'No'],
       [73, 1, 98.0, 0.0, 0, 0, 0, 'Yes'],
       [71, 0, 98.0, 1.0, 0, 1, 0, 'Yes'],
       [80, 

# The above hectic code can be done in the few lines using **Column Transformer**

In [237]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(missing_values=np.nan, strategy='most_frequent'),['fever']),
    ('tnf2',OneHotEncoder(sparse_output=False,dtype=int,drop='first'),['city','gender']),
    ('tnf3',OrdinalEncoder(categories=[['Mild','Strong']]),['cough'])
] ,remainder='passthrough')

In [238]:
transformer.fit_transform(df)

array([[103.0, 0, 1, 0, 1, 0.0, 60, 'No'],
       [100.0, 1, 0, 0, 1, 0.0, 27, 'Yes'],
       [101.0, 1, 0, 0, 1, 0.0, 42, 'No'],
       [98.0, 0, 1, 0, 0, 0.0, 31, 'No'],
       [101.0, 0, 0, 1, 0, 0.0, 65, 'No'],
       [98.0, 0, 0, 0, 0, 0.0, 84, 'Yes'],
       [101.0, 0, 0, 0, 1, 1.0, 14, 'No'],
       [98.0, 0, 0, 1, 0, 1.0, 20, 'Yes'],
       [100.0, 0, 0, 0, 0, 1.0, 19, 'No'],
       [101.0, 1, 0, 0, 0, 0.0, 64, 'No'],
       [98.0, 1, 0, 0, 0, 0.0, 75, 'No'],
       [98.0, 0, 0, 1, 0, 0.0, 65, 'Yes'],
       [99.0, 0, 1, 0, 0, 1.0, 25, 'No'],
       [102.0, 0, 0, 0, 1, 0.0, 64, 'Yes'],
       [104.0, 0, 0, 0, 1, 0.0, 51, 'No'],
       [103.0, 0, 1, 0, 1, 1.0, 70, 'Yes'],
       [103.0, 0, 1, 0, 0, 0.0, 69, 'Yes'],
       [98.0, 1, 0, 0, 0, 1.0, 40, 'No'],
       [98.0, 0, 0, 0, 0, 0.0, 64, 'Yes'],
       [98.0, 0, 0, 0, 0, 1.0, 42, 'Yes'],
       [98.0, 0, 0, 0, 1, 1.0, 12, 'No'],
       [98.0, 0, 0, 0, 1, 0.0, 73, 'Yes'],
       [98.0, 0, 1, 0, 0, 1.0, 71, 'Yes'],
       [98.0